### ISSUE TITLE
TypeError: can't compare datetime.date to QDate

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#102]
When selecting date column type, I get the following error. 

```
An error has occurred while executing Python code: 
TypeError: can't compare datetime.date to QDate
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\wizard\column_editor.py", line 624, in accept
    self.column = self.create_column()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\wizard\column_editor.py", line 504, in create_column
    self.entity, **self.form_fields)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\columns.py", line 455, in __init__
    BoundsColumn.__init__(self, *args, **kwargs)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\columns.py", line 308, in __init__
    self.minimum = self.SQL_MIN
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\columns.py", line 288, in __setattr__
    object.__setattr__(self, key, value)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\columns.py", line 338, in minimum
    if val > self._maximum:
TypeError: can't compare datetime.date to QDate

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

```

**Comment by gkahiu** [comment]
Dear Paul,

Please convert the data types for the selected date from QDate to PyDate.
Refer to the API here
<http://pyqt.sourceforge.net/Docs/PyQt4/qdate.html#toPyDate>.

Regards

**Comment by pgathogo** [comment]
Fixed. 
For Date type default minimum value is `datatime.date.min `and maximum value is `datetieme.date.max`

**Comment by pgathogo** [comment]
Fixed.
Datetime type minimum value is `datetime.datetime.min` and `datetime.datetime.max` for maximum value.
