### ISSUE TITLE
Error when using the word documents for columns in the wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#104]
When using the word 'documents' for column name, I get the following error. 

```
An error has occurred while executing Python code: 
ArgumentError: Error creating backref 'documents' on relationship 'EntitySupportingDocumentProxy.fa_spatial_unit': property of that name exists on mapper 'Mapper|fa_spatial_unit|fa_spatial_unit' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\spatial_unit_manager.py", line 189, in init_form_widgets
    STDM_WIDGET.set_mapper()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\spatial_unit_form.py", line 86, in set_mapper
    self.mapper = MapperMixin(model)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\mapping.py", line 144, in __init__
    self._model = model()
  File "", line 2, in __init__
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\instrumentation.py", line 324, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\langhelpers.py", line 725, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\instrumentation.py", line 158, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\event\attr.py", line 260, in __call__
    fn(*args, **kw)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 2693, in _event_on_first_init
    configure_mappers()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 2589, in configure_mappers
    mapper._post_configure_properties()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 1694, in _post_configure_properties
    prop.init()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\interfaces.py", line 144, in init
    self.do_init()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\relationships.py", line 1553, in do_init
    self._generate_backref()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\relationships.py", line 1743, in _generate_backref
    (backref_key, self, m))
ArgumentError: Error creating backref 'documents' on relationship 'EntitySupportingDocumentProxy.fa_spatial_unit': property of that name exists on mapper 'Mapper|fa_spatial_unit|fa_spatial_unit'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 
Python Path:
•	C:/Users/Wondim/.qgis2/python/plugins\processing
•	C:/PROGRA~1/QGISES~1/apps/qgis/./python
•	C:/Users/Wondim/.qgis2/python
•	C:/Users/Wondim/.qgis2/python/plugins
•	C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
•	c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
•	C:\PROGRA~1\QGISES~1\bin\python27.zip
•	C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
•	C:\PROGRA~1\QGISES~1\bin
•	C:\PROGRA~1\QGISES~1\apps\Python27
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
•	C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
•	C:/Users/Wondim/.qgis2//python
•	C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
•	C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools


```

**Comment by gkahiu** [comment]
Dear Paul,

Please have a list of reserved column names which cannot be specified by
the user starting with:

   - id
   - documents

Regards,

John

**Comment by pgathogo** [comment]
Fixed. The column name is now checked against the reserved keywords before saving.
Currently am using the following reserved keywords;
 - id
- documents
- spatial_unit, 
- supporting_document
- social_tenure
- social_tenure_relationship

Regards,

Paul
