### ISSUE TITLE
Failed to open New str wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#107]
When I start New STR Wizard, I got a python error that says AttributeError: 'NoneType' object has no attribute 'TYPE_INFO'. I have checked all the entities that use foriegnkey mapper are not none. 

```

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'TYPE_INFO' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\plugin.py", line 1542, in widgetLoader
    self.newSTR()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\plugin.py", line 1068, in newSTR
    frmNewSTR = newSTRWiz(self)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 157, in __init__
    self.init_spatial_unit_add()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 361, in init_spatial_unit_add
    self.spatial_unit_notice
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 693, in _create_fk_mapper
    fk_mapper.setSupportsList(True)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 265, in __init__
    self._init_fk_columns()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 327, in _init_fk_columns
    formatter = w_factory(c)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\widgets.py", line 423, in __init__
    self._p_entity_cls = entity_model(p_entity, entity_only=True)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\configuration\__init__.py", line 65, in entity_model
    if entity.TYPE_INFO == 'ENTITY_SUPPORTING_DOCUMENT':
AttributeError: 'NoneType' object has no attribute 'TYPE_INFO'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
```

**Comment by gkahiu** [comment]
Dear Wondie,

I have successfully loaded the new STR wizard and select a party record
using the foreign key mapper. Please check your merge or STDM configuration.

Regards,

John

**Comment by wondie** [comment]
Dear John, 

I didn't face any merge conflict errors.

**Comment by wondie** [comment]
After starting from scratch, the new str wizard works!
