### ISSUE TITLE
Failed to choose related table for related column

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#108]
When I tried to load a related entity from the form widget on QGIS Form and also attribute table widget, I get the following error. The issue is not there in entity browser or forms. It looks like it is related to [this issue. 
](https://github.com/gltn/stdm/issues/107)
```

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'short_name' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\customcontrols\relation_line_edit.py", line 207, in on_load_foreign_key_browser
    eb = EntityBrowser(parent_entity, parent=self.parent(), state=SELECT)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\entity_browser.py", line 126, in __init__
    entity.short_name,
AttributeError: 'NoneType' object has no attribute 'short_name'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
```

**Comment by gkahiu** [comment]
I have successfully loaded and selected a record using the related entity
control. As mentioned in the previous, please check whether there were
merge conflicts (and how you resolved them) or check your configuration.

Regards,

John

**Comment by wondie** [comment]
I didn't get any report of merge conflict. Did you try to load it with spatial unit forms? It also works for me for other forms.

**Comment by wondie** [comment]
After deleting the profile and database and re-creating new ones, the new related entity works!
