### ISSUE TITLE
Couldn't use a social tenure type lookup multiple times

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#109]
I created a new configuration from scratch. In doing so, I used tenure_type in spatial unit entity but I got the following issue when trying to open New STR Wizard.

And, after deleting the column tenure_type from spatial unit entity, I still got the error shown below. So it means, when a column is deleted using the wizard, all related foreign keys are not deleted. 
 I hope it is not the same for other lookups.
```

An error has occurred while executing Python code: 

ArgumentError: Error creating backref 'tu_spatial_unit_collection' on relationship 'tu_spatial_unit.tu_check_tenure_type': property of that name exists on mapper 'Mapper|tu_check_tenure_type|tu_check_tenure_type' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\plugin.py", line 1546, in widgetLoader
    self.newSTR()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\plugin.py", line 1072, in newSTR
    frmNewSTR = newSTRWiz(self)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 157, in __init__
    self.init_spatial_unit_add()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 361, in init_spatial_unit_add
    self.spatial_unit_notice
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\new_str_wiz.py", line 691, in _create_fk_mapper
    fk_mapper = ForeignKeyMapper(config.ds_entity, parent, notif_bar)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 265, in __init__
    self._init_fk_columns()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\foreign_key_mapper.py", line 327, in _init_fk_columns
    formatter = w_factory(c)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\widgets.py", line 483, in __init__
    self._aus_obj = self._aus_cls()
  File "", line 2, in __init__
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\instrumentation.py", line 324, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\langhelpers.py", line 725, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\instrumentation.py", line 158, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\event\attr.py", line 260, in __call__
    fn(*args, **kw)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 2693, in _event_on_first_init
    configure_mappers()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 2589, in configure_mappers
    mapper._post_configure_properties()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\mapper.py", line 1694, in _post_configure_properties
    prop.init()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\interfaces.py", line 144, in init
    self.do_init()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\relationships.py", line 1553, in do_init
    self._generate_backref()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\relationships.py", line 1743, in _generate_backref
    (backref_key, self, m))
ArgumentError: Error creating backref 'tu_spatial_unit_collection' on relationship 'tu_spatial_unit.tu_check_tenure_type': property of that name exists on mapper 'Mapper|tu_check_tenure_type|tu_check_tenure_type'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
```

**Comment by pgathogo** [comment]
Fixed. Removed the 'social tenure type lookup' from the selection list of lookups when creating a lookup column.

**Comment by wondie** [comment]
That is good Paul.
