### ISSUE TITLE
DB Related error blocks user from further DB queries. 

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#111]
@gkahiu this issue was what I wanted to share with you a while back. 
After any DB related error, when a user tries to do anything related to database, such as SELECT, the following error happens. Please ignore the original issue. I am testing something. 

This forces the user to restart QGIS or STDM. 

Is there a fix for it?
```

An error has occurred while executing Python code: 

InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) can't adapt type 'QDate' 'INSERT INTO tu_party (name, admin_spatial_unit, date_of, date_time) VALUES (%(name)s, %(admin_spatial_unit)s, %(date_of)s, %(date_time)s) RETURNING tu_party.id' {'date_time': PyQt4.QtCore.QDateTime(7999, 12, 31, 23, 59, 59, 999), 'date_of': PyQt4.QtCore.QDate(2016, 7, 11), 'name': u'', 'admin_spatial_unit': None} 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\entity_browser.py", line 701, in onNewEntity
    addEntityDlg = self._editor_dlg(self._entity, parent=self)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 114, in __init__
    self._init_gui()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 128, in _init_gui
    column_widget_area = self._setup_columns_content_area()
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\editor_dialog.py", line 242, in _setup_columns_content_area
    self
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\forms\documents.py", line 109, in __init__
    self
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\sourcedocument.py", line 108, in __init__
    doc_type_list = doc_type_obj.queryObject().all()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\query.py", line 2320, in all
    return list(self)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\query.py", line 2451, in _execute_and_instances
    close_with_result=True)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\query.py", line 2442, in _connection_from_session
    **kw)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 854, in connection
    close_with_result=close_with_result)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 858, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 305, in _connection_for_bind
    self._assert_active()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) can't adapt type 'QDate' 'INSERT INTO tu_party (name, admin_spatial_unit, date_of, date_time) VALUES (%(name)s, %(admin_spatial_unit)s, %(date_of)s, %(date_time)s) RETURNING tu_party.id' {'date_time': PyQt4.QtCore.QDateTime(7999, 12, 31, 23, 59, 59, 999), 'date_of': PyQt4.QtCore.QDate(2016, 7, 11), 'name': u'', 'admin_spatial_unit': None}


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
```

**Comment by gkahiu** [comment]
I will modify the Model class and let you know so that you can retest.

Regards,

John

**Comment by wondie** [comment]
Ok that is great!

**Comment by wondie** [comment]
I realized that using STDMDb.instance().session.rollback() as used in [new_str_wizard](https://github.com/gltn/stdm/blob/ref_config_mod/ui/new_str_wiz.py#L1279) could solve it but doing this on each DB query could be overwhelming. As you have said, it will be great to include it the STDMDB class.

**Comment by gkahiu** [comment]
I see already exception handling for the CRUD methods in the Model class. Is it issue fixed?

**Comment by wondie** [comment]
Yes it is added for the CRUD methods. In other areas of modules of STDM. However, for other classes if they are not using the CRUD methods, we have to add session.rollback() individually.

**Comment by wondie** [comment]
I have incorporated more session.rollback() in two more methods notably queryObject and _execute() in [this commit](https://github.com/gltn/stdm/commit/8355f2d4ecdc550beaf95e6c184eeaac81d6c6a3). I have removed the print in [this commit](https://github.com/gltn/stdm/commit/d61e305969f6b11ffdaece2a2315590fc04afe5c) :) I can assume this issue is fixed. However, I have included it in the STDM coding stands.
