### ISSUE TITLE
GeoAlchemy Error

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#17]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 208, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "~/.qgis2/python/plugins/stdm/__init__.py", line 38, in classFactory
    from stdm import STDMQGISLoader
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/stdm.py", line 29, in 
    from ui import (loginDlg,
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/ui/__init__.py", line 1, in 
    from .login_dlg import loginDlg
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/ui/login_dlg.py", line 24, in 
    from .db_conn_dlg import dbconnDlg
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tux/.qgis2/python/plugins/stdm/ui/db_conn_dlg.py", line 24, in 
    from stdm.data import DatabaseConnection, DatabaseConfig
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/data/__init__.py", line 3, in 
    from database import STDMDb,Base,Model
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/data/database.py", line 32, in 
    from geoalchemy2 import Geometry
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/third_party/geoalchemy2/__init__.py", line 1, in 
    from .types import (  # NOQA
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/third_party/geoalchemy2/types.py", line 15, in 
    from .comparator import BaseComparator, Comparator
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.qgis2/python/plugins/stdm/third_party/geoalchemy2/comparator.py", line 52, in 
    class BaseComparator(UserDefinedType.Comparator):
AttributeError: type object 'UserDefinedType' has no attribute 'Comparator'

**Comment by gkahiu** [comment]
Cannot reproduce this in my installation. Does this error occur when QGIS is starting up or when you attempt to log into STDM?

**Comment by eomwandho** [comment]
The error occurs when QGIS starts. I upgraded my QGIS to version 2.6.1 and running under Ubuntu 12.04 LTS, could this be the reason? Before it was running Okay.

**Comment by SolomonN** [comment]
I think at some point I had that experience and resolved it by upgrading geoalchemy2 to the latest version. Kind Regards,
Solomon.Mobile +254 724 291046 

     On Monday, January 5, 2015 11:54 AM, eomwandho <notifications@github.com> wrote:
   

 The error occurs when QGIS starts. I upgraded my QGIS to version 2.6.1 and running under Ubuntu 12.04 LTS, could this be the reason? Before it was running Okay.—

**Comment by gkahiu** [comment]
Could you try it in QGIS 2.4 as we have not yet fully tested in 2.6 due to some changes in the pyqgis API. Let me know.

**Comment by eomwandho** [comment]
As suggested by Solomon, after the upgrade of GeoAlchemy to version 2. The plugin now works fine. **Note** For users still using Ubuntu 12.04 LTS, they will have also to manually upgrade SQLAlchemy to version 0.8 as GeoAlchemy 2 depends on it and the default version is still version 0.7 on Ubuntu default package installer. 

Now I'm experiencing some issues with resource file resources_rc. The file exists in the module, though it it can't seem to be imported from the file ui_adminUnitManager.py. This is shown in the error below.

File "~/.qgis2/python/plugins/stdm/ui/ui_adminUnitManager.py", line 96, in 
    import resources_rc
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources_rc

**Comment by SolomonN** [comment]
Dear Eric,
I think is becoming a common issue in ubuntu that the resource file is not being referenced properly, I guess this is because the the relative paths in windows and Ubuntu to the resource location do not match. At the moment, you might want to copy the file manually in the folders with files unable to locate it.  Kind Regards,
Solomon.Mobile +254 724 291046 

     On Monday, January 5, 2015 12:45 PM, eomwandho <notifications@github.com> wrote:
   

 As suggested by Solomon, after the upgrade of GeoAlchemy to version 2. The plugin now works fine. Note For users still using Ubuntu 12.04 LTS, they will have also to manually upgrade SQLAlchemy to version 0.8 as GeoAlchemy 2 depends on it and the default version is still version 0.7 on Ubuntu default package installer. Now I'm experiencing some issues with resource file resources_rc. The file exists in the module, though it it can't seem to be imported from the file ui_adminUnitManager.py. This is shown in the error below.File "~/.qgis2/python/plugins/stdm/ui/ui_adminUnitManager.py", line 96, in 
 import resources_rc
 File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 460, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources_rc—
