### ISSUE TITLE
Stack trace when opening admin unit form widget

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#176]
This issue happened after adding a record in related entity collection and click on the **Save** button without filling the required field in the primary tab as shown below. 
![image](https://cloud.githubusercontent.com/assets/9709624/18488218/312d5476-7a01-11e6-99b7-14c8b348bc2e.png)

The primary tab is shown below. 
![image](https://cloud.githubusercontent.com/assets/9709624/18488295/6c997ef4-7a01-11e6-9a29-a5d58fa3e700.png)

The stack trace below is shown when I was click on the Administrative unit widget in the **primary** tab. 
```

An error has occurred while executing Python code: 

IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) null value in column "household_id" violates not-null constraint DETAIL:  Failing row contains (4, null, null). 'INSERT INTO in_household (location, household_id) VALUES (%(location)s, %(household_id)s) RETURNING in_household.id' {'household_id': None, 'location': None} 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\customcontrols\relation_line_edit.py", line 349, in on_load_foreign_key_browser
    au_selector = AdminUnitSelector(self.parent())
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\admin_unit_selector.py", line 35, in __init__
    self.adminUnitManager = AdminUnitManager(self)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\admin_unit_manager.py", line 144, in __init__
    self._adminUnitNodeFormatter.root(),
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\admin_unit_manager.py", line 80, in root
    for aus in adminUnits:
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\query.py", line 2437, in __iter__
    self.session._autoflush()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 1198, in _autoflush
    self.flush()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 526, in execute
    uow
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) null value in column "household_id" violates not-null constraint
DETAIL:  Failing row contains (4, null, null).
 'INSERT INTO in_household (location, household_id) VALUES (%(location)s, %(household_id)s) RETURNING in_household.id' {'household_id': None, 'location': None}


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm_ref_config\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm_ref_config\third_party\fo
```ntTools

**Comment by gkahiu** [comment]
Strange that it the value did not get validated prior to being saved. I will have a look at it and fix it.

**Comment by wondie** [comment]
It validates it and even shows warning message on the message bar. But the stake trace is shown when trying to click on the Administrative unit widget.

**Comment by gkahiu** [comment]
Please confirm if [2b6e2b2](https://github.com/gltn/stdm/commit/2b6e2b2ea6c723598b1d8e408c3681188e7289a7) fixes the issue.

**Comment by wondie** [comment]
This issue is now fixed.
