### ISSUE TITLE
Stack trace when opening a template in Document Designer

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#195]
I got a stack trace when opening a template that was created for an earlier version of the same profile. The profile has seen changes over time such as changes in entity and column. It was able to open the template but it shown the following error. 

```

An error has occurred while executing Python code: 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\composer\composer_item_config.py", line 452, in on_action_triggered
    self.composerWrapper().create_new_document_designer(file_path)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\composer\composer_wrapper.py", line 446, in create_new_document_designer
    cw.loadTemplate(file_path)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\composer\composer_wrapper.py", line 510, in loadTemplate
    self._configureSpatialSymbolEditor(spatialFieldsConfig)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\composer\composer_wrapper.py", line 699, in _configureSpatialSymbolEditor
    composerSymbolEditor.add_spatial_field_mappings(spFieldsMappings)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\composer\composer_symbol_editor.py", line 186, in add_spatial_field_mappings
    self.add_spatial_field_mapping(sfm)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\composer\composer_symbol_editor.py", line 192, in add_spatial_field_mapping
    self.add_styling_widget(sp_field_mapping)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\composer\composer_symbol_editor.py", line 230, in add_styling_widget
    sp_field_mapping
TypeError: 'NoneType' object is not iterable


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

```

**Comment by gkahiu** [comment]
Can you send the template?

**Comment by wondie** [comment]
Please find the attached template. 
[uganda_customary_v1.zip](https://github.com/gltn/stdm/files/556529/uganda_customary_v1.zip)

**Comment by gkahiu** [comment]
Well, the template opened in my setup, see screenshot below:
![customary certificate](https://cloud.githubusercontent.com/assets/3840267/19797592/cf701536-9cf4-11e6-94e5-502f79812e95.PNG)

**Comment by wondie** [comment]
That is true, the template opens but a stack trace is also shown.

**Comment by gkahiu** [comment]
When do you get the stack trace as I did not get one?

**Comment by wondie** [comment]
It is shown as soon as the template loads.

**Comment by gkahiu** [comment]
I did not get the stack trace.

**Comment by wondie** [comment]
This is how the stack trace appears for me. 

![image](https://cloud.githubusercontent.com/assets/9709624/19798950/8d272cf2-9cfc-11e6-9723-f864a200024b.png)

**Comment by gkahiu** [comment]
No errors for me, been unable to reproduce it.

**Comment by wondie** [comment]
Ok I will show you when we meet but I feel it is caused by a mismatch of columns and tables so it is not a big issue.

**Comment by wondie** [comment]
This issue is fixed with[ this commit](https://github.com/gltn/stdm/commit/1b705d62295fb8083e2e459bb342195c4d4091f6).
