### ISSUE TITLE
Unable to save configuration before defining STR

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#212]
Hi @gkahiu ,

It is not possible to save a profile before defining a social tenure relationship. This issue came about when we were testing the saving of profile as draft in my branch 'config_wiz'. 
To reproduce the problem, create a new profile, add some entities then select 'Save draft', you will get a stack trace shown below.

A closer look reveals missing checks in the config_serializer. It seems when you call `ConfigurationFileSerializer.save()` method (usually at the end of the configuration process) the STR should already be defined.

To see this issues, kindly check out my branch 'config_wiz'

```
AttributeError: 'NoneType' object has no attribute 'short_name' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 1260, in save_draft
    self.save_current_configuration(DRAFT_CONFIG_FILE)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 1227, in save_current_configuration
    cfs.save()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 114, in save
    self.write_xml(config_document)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 133, in write_xml
    ProfileSerializer.write_xml(p, config_element, document)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 518, in write_xml
    profile_element, document)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 676, in write_xml
    social_tenure.spatial_unit.short_name)
AttributeError: 'NoneType' object has no attribute 'short_name'
```

**Comment by gkahiu** [comment]
Hi Paul,

The assumption was that there profile will be complete including all social tenure definitions but also I should have incorporated a check for the main STR entity.

Please modify the code [here](https://github.com/gltn/stdm/blob/config_wiz/settings/config_serializer.py#L675) to add a check i.e.
```
sp_unit_name = ''
if not social_tenure.spatial_unit is None:
    sp_unit_name = social_tenure.spatial_unit.short_name
 
social_tenure_element.setAttribute(SocialTenureSerializer.SPATIAL_UNIT,
                                        sp_unit_name)
```

Check if there are other sections within the serializer that need to be updated.

**Comment by pgathogo** [comment]
Issue has been fixed on branch config_wiz.
