### ISSUE TITLE
Unable to delete lookup value in the Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#234]
I couldn't delete a lookup value. Nothing happens when I select a value and press the delete button.

**Comment by pgathogo** [comment]
@wondie ,

Actually something happens, a stack trace!

An error has occurred while executing Python code: 

AttributeError: 'unicode' object has no attribute 'value' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 2344, in delete_lookup_value
    lookup.remove_value(unicode(value_text))
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\value_list.py", line 255, in remove_value
    digest = self.value_hash(value.value)
AttributeError: 'unicode' object has no attribute 'value'

**Comment by wondie** [comment]
This issue is now fixed in [this commit](https://github.com/gltn/stdm/commit/3f6fa8e41e6d37516967d5237302d13b1360a7d9).
