### ISSUE TITLE
Error reading configuration file from an earlier version

### ISSUE THREAD

**Issue by SolomonN** [gltn/stdm#240]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 8: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 201, in on_update_complete
    self._load_config_items(doc_element)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 308, in _load_config_items
    self.config)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 428, in read_xml
    entity_relation_elements)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 1374, in read_xml
    value_list.add_value(value, code)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\value_list.py", line 122, in add_value
    self.add_code_value(CodeValue(value=value, code=code))
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\value_list.py", line 141, in add_code_value
    digest = self.value_hash(code_value.value)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\value_list.py", line 132, in value_hash
    lookup_value = self._hash.md5(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 8: ordinal not in range(128)

**Comment by wondie** [comment]
Which version of STDM are you using?

**Comment by wondie** [comment]
Could you pull the latest master and see if the issue is fixed?

**Comment by gkahiu** [comment]
@SolomonN was this issue resolved so that we close it?

**Comment by SolomonN** [comment]
Hello John,Last time I tested was not solved last week was not working. I will try it again to confirm. Kind Regards,
Solomon Njogu.Land Management Land Tenure - TUM, Germany.Mobile +254 724 291046, +4915218657520 

    On Friday, July 14, 2017 7:38 PM, Kahiu <notifications@github.com> wrote:
 

 @SolomonN was this issue resolved so that we close it?—
