### ISSUE TITLE
Stack trace when saving configuration

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#241]
Hello,
Am getting a stack trace during the process of saving the configuration. This is happening with the latest master branch.

```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'name' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 1223, in _updater_thread_started
    self.config_updater.exec_()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\config_updater.py", line 100, in exec_
    self.update_profile(p)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\config_updater.py", line 206, in update_profile
    profile.social_tenure.create_view(self.engine)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\social_tenure.py", line 881, in create_view
    self.view_creator(engine)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\social_tenure_updater.py", line 86, in view_updater
    _create_primary_entity_view(social_tenure, pe, v)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\social_tenure_updater.py", line 114, in _create_primary_entity_view
    if not social_tenure.is_str_party_entity(primary_entity):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\social_tenure.py", line 658, in is_str_party_entity
    return self._party_in_parties(entity)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\data\configuration\social_tenure.py", line 632, in _party_in_parties
    if party.name in party_names:
```
AttributeError: 'NoneType' object has no attribute 'name'

regards.

**Comment by gkahiu** [comment]
Which commit are you using? @wondie could you look into code for creating the views?

**Comment by wondie** [comment]
Could you pull the latest commit? I am not getting time.

**Comment by pgathogo** [comment]
Am using the latest commit.

**Comment by wondie** [comment]
I think you still have an older version. When I compared the stack trace lines and the current master online, they are in different. 
Line 86 on your stack trace is located at line [93](https://github.com/gltn/stdm/blob/master/data/configuration/social_tenure_updater.py#L93). 
Line 114 on your stack trace is located at line [121](https://github.com/gltn/stdm/blob/master/data/configuration/social_tenure_updater.py#L121).

**Comment by pgathogo** [comment]
@wondie, I just did a "git pull"  and am still getting the stack trace. Anything I need to check?

**Comment by wondie** [comment]
Could you share the new stack trace?

**Comment by wondie** [comment]
@pgathogo I also discovered this issue. It will be fixed soon but I suggest you to use the stable 1.6.2 until the issue is fixed.

**Comment by pgathogo** [comment]
@wondie , noted.

**Comment by gkahiu** [comment]
@pgathogo @wondie, is this issue resolved?

**Comment by wondie** [comment]
@gkahiu if you remember, we are waiting for you as the issue is related with social_tenure.py

**Comment by gkahiu** [comment]
@pgathogo I have committed a fix related to views so please pull from master and check whether this issue is resolved?

**Comment by pgathogo** [comment]
@gkahiu, noted.

**Comment by pgathogo** [comment]
This issue is now resolved.
