### ISSUE TITLE
Stack Trace when renaming Entity in the Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#262]
I get the following stack trace when I try to change the name of an entity.
```

An error has occurred while executing Python code: 

TypeError: Entity object type expected. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\create_entity.py", line 162, in accept
    self.edit_entity(short_name)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\create_entity.py", line 191, in edit_entity
    status = self.profile.rename(old_short_name, short_name)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\data\configuration\profile.py", line 605, in rename
    parent_relations = self.parent_relations(ent)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\data\configuration\profile.py", line 273, in parent_relations
    raise TypeError(self.tr('Entity object type expected.'))
TypeError: Entity object type expected.


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.3 Las Palmas, 77b8c3d 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGIS2~1.18\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGIS2~1.18\apps\qgis\python\plugins\stdm\third_party\fontTools
```

**Comment by pgathogo** [comment]
@wondie, what branch are your working on? I tried on my master branch but I could not reproduce the issue.

**Comment by wondie** [comment]
Hi Paul,
It is master.

**Comment by pgathogo** [comment]
@wondie , is this issue still open? I was unable to reproduce it.

**Comment by wondie** [comment]
Hi Paul,

I encountered it yesterday.

**Comment by wondie** [comment]
This is the error message shown now. 
```
An error has occurred while executing Python code: 

AttributeError: 'OrderedDict' object has no attribute 'rename' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 2206, in edit_column
    entity.rename_column(original_column.name, editor.column.name)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\data\configuration\entity.py", line 241, in rename_column
    self.columns.rename(old_name, new_name)
AttributeError: 'OrderedDict' object has no attribute 'rename'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.3 Las Palmas, 77b8c3d 
```

**Comment by wondie** [comment]
I am able to reproduce this issue still but this time the first edit was ok but the second and third edits showed this stack trace. 

![image](https://user-images.githubusercontent.com/9709624/34051370-60dd1bc0-e1cf-11e7-97e5-8198910f13aa.png)

**Comment by pgathogo** [comment]
This issues is now fixed.

**Comment by wondie** [comment]
I have check that it is fixed.
