### ISSUE TITLE
Stack trace when editing columns

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#267]
The stack trace below is shown when editing columns in the wizard. 
```
An error has occurred while executing Python code: 

AttributeError: 'OrderedDict' object has no attribute 'rename' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 2206, in edit_column
    entity.rename_column(original_column.name, editor.column.name)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\data\configuration\entity.py", line 241, in rename_column
    self.columns.rename(old_name, new_name)
AttributeError: 'OrderedDict' object has no attribute 'rename'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.3 Las Palmas, 77b8c3d 

```

**Comment by pgathogo** [comment]
Issue is now fixed
