### ISSUE TITLE
Discarding draft causes stack trace

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#276]
I get the following error when I discard a draft configuration. 
```

An error has occurred while executing Python code: 

AttributeError: 'RenameableKeyDict' object has no attribute 'has_key' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 1957, in eventFilter
    self.drop_column_event(event)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 1944, in drop_column_event
    entity.update_column_row_index(col_name, row)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\stdm\data\configuration\entity.py", line 526, in update_column_row_index
    if self.columns.has_key(name):
AttributeError: 'RenameableKeyDict' object has no attribute 'has_key'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.3 Las Palmas, 77b8c3d 


```

**Comment by pgathogo** [comment]
Unable to re-create this issue, please confirm.

**Comment by wondie** [comment]
That is good. This issue must have been fixed in previous commits.
