### ISSUE TITLE
Deleting a copied profile results in stack trace

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#281]
Deleting a copied profile results in the following stack trace.
```

An error has occurred while executing Python code: 

TypeError: Entity object type expected. 
Traceback (most recent call last):
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 1721, in delete_profile
    if not self.stdm_config.remove_profile(profile_name):
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\configuration\stdm_configuration.py", line 134, in remove_profile
    del_profile.on_delete()
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\configuration\profile.py", line 564, in on_delete
    self.remove_entity(entity.short_name)
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\configuration\profile.py", line 404, in remove_entity
    parent_relations = self.parent_relations(ent)
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\configuration\profile.py", line 275, in parent_relations
    raise TypeError(self.tr('Entity object type expected.'))
TypeError: Entity object type expected.


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, ff83b9a479 

```

**Comment by pgathogo** [comment]
Unable to reproduce this issue on my end, everything is working as expected.

**Comment by wondie** [comment]
I couldn't reproduce it today too. I will close it for now.
