### ISSUE TITLE
Stack trace when adding an STDM view layer

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#282]
Am getting the following stack trace when adding a view layer.

Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\spatial_unit_manager.py", line 626, in on_add_to_canvas_button_clicked
    self.join_fk_layer(curr_layer)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\spatial_unit_manager.py", line 192, in join_fk_layer
    for column in entity.columns.values():
AttributeError: 'NoneType' object has no attribute 'columns'

![image](https://user-images.githubusercontent.com/155431/33470351-e64449f8-d678-11e7-9f15-4821a3aeae59.png)

**Comment by wondie** [comment]
Thank for finding this issue. I will fix and and report.

**Comment by wondie** [comment]
@pgathogo this issue is now fixed in [this commit.](https://github.com/gltn/stdm/commit/3e811f7bdbd96248ab9a1da00e2125fcaae9f0bb)

**Comment by pgathogo** [comment]
This is issue is now fixed.
