### ISSUE TITLE
Stack trace when starting GeoODK

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#295]
@SolomonN the following stack trace happens when starting Import Mobile data menu. 
```

An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\plugin.py", line 1963, in mobile_form_importer
    importer_dialog = ProfileInstanceRecords(self.iface.mainWindow())
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\geoodk_profile_importer.py", line 107, in __init__
    self.current_profile_changed()
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\geoodk_profile_importer.py", line 154, in current_profile_changed
    self.profile_instance_entities()
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\geoodk_profile_importer.py", line 264, in profile_instance_entities
    entity_list = self.instance_entities()
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\geoodk_profile_importer.py", line 300, in instance_entities
    self.uuid_extractor.set_file_path(os.path.join(dir_f, instance_file[0]))
IndexError: list index out of range


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.16 Las Palmas, d473c3071a 

Python Path:
C:/OSGEO4~1/apps/qgis/./python/plugins\processing
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/Wondim/.qgis2//python
C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party
C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\fontTools
```

**Comment by wondie** [comment]
This issue is not fixed in [this commit](https://github.com/gltn/stdm/commit/cb381c2ff835b0b04f518f7f8e3425e483abcf03).
