### ISSUE TITLE
Strack Trace When Deleting an Administrative Unit

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#304]
This error message happens when deleting administrative unit twice. On the first case there is no error and on the second attempt it throws the error below. 
```
An error has occurred while executing Python code: 

ProgrammingError: (ProgrammingError) can't adapt type 'Table' 'SELECT column_name,table_name,foreign_column_name, constraint_name FROM foreign_key_references where foreign_table_name =%(tb_name)s' {'tb_name': Table('admin_spatial_unit_set', MetaData(bind=None), Column('id', Integer(), table=, primary_key=True, nullable=False), Column('parent_id', Integer(), ForeignKey('admin_spatial_unit_set.id'), table=), Column('name', String(length=50), table=), Column('code', String(length=10), table=), schema=None)} 
Traceback (most recent call last):
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\ui\admin_unit_manager.py", line 345, in onDeleteSelection
    ausObj.delete()
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\database.py", line 279, in delete
    set_child_dependencies_null_on_delete(self.__table__)
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\pg_utils.py", line 919, in set_child_dependencies_null_on_delete
    deps = foreign_key_parent_tables(table, False)
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\pg_utils.py", line 646, in foreign_key_parent_tables
    result = _execute(t, tb_name=table_name)
  File "C:/Users/Wondim/.qgis2/python/plugins\stdm\data\pg_utils.py", line 532, in _execute
    result = conn.execute(sql,**kwargs)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) can't adapt type 'Table' 'SELECT column_name,table_name,foreign_column_name, constraint_name FROM foreign_key_references where foreign_table_name =%(tb_name)s' {'tb_name': Table('admin_spatial_unit_set', MetaData(bind=None), Column('id', Integer(), table=, primary_key=True, nullable=False), Column('parent_id', Integer(), ForeignKey('admin_spatial_unit_set.id'), table=), Column('name', String(length=50), table=), Column('code', String(length=10), table=), schema=None)}


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.4 Las Palmas, 59c1d21 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party
C:\Users\Wondim\.qgis2\python\plugins\stdm\third_party\fontTools
```

**Comment by gkahiu** [comment]
I have been unable to reproduce it. By deleting twice, do you mean:
1. I delete administrative unit name A (first time);
2. Recreate administrative unit name A;
3. Attempt to delete administrative unit name A again?

Are there columns of Administrative Spatial Unit type that have been created? If so:
1. Are there rows in other related tables that refer to administrative unit name A?
2. What is the DELETE policy of these columns in the database e.g. NO ACTION, SET NULL, CASCADE; see example below:
![image](https://user-images.githubusercontent.com/3840267/37256279-52903f38-2569-11e8-91b6-6eeb9e4625f7.png)

**Comment by wondie** [comment]
What I mean in the second Administrative unit is, another administrative unit. I think there is no relation to the order. The cause is that the administrative unit is used by other tables for instance the local Government. This is the SQL of administrative unit. 
```
CREATE TABLE public.admin_spatial_unit_set
(
    id integer NOT NULL DEFAULT nextval('admin_spatial_unit_set_id_seq'::regclass),
    parent_id integer,
    name character varying(50) COLLATE pg_catalog."default",
    code character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT admin_spatial_unit_set_pkey PRIMARY KEY (id),
    CONSTRAINT admin_spatial_unit_set_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES public.admin_spatial_unit_set (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

```
The database is created and used by an older version of STDM. This is a problem that may happen on people using the older STDM database.

**Comment by wondie** [comment]
I also checked the parcel table using and below is the constraint. 
```
    CONSTRAINT lo_parcel_location_fkey FOREIGN KEY (location)
        REFERENCES public.admin_spatial_unit_set (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
```
