### ISSUE TITLE
No module named resources_rc error

### ISSUE THREAD

**Issue by olivierdalang** [gltn/stdm#36]
Hi !

I have some problem installing the plugin. I tried to install manually (by copying the source folder to the QGIS plugins folder), which I prefer since I already have QGIS and Postgis installed, and I tried using the .exe installer, but both fail with this error at the opening of QGIS:

**ImportError: No module named resources_rc**

```
Couldn't load plugin stdm due to an error when calling its classFactory() method


Traceback (most recent call last):
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Olivier/.qgis2/python/plugins\stdm\__init__.py", line 38, in classFactory
    from stdm import STDMQGISLoader
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Olivier/.qgis2/python/plugins\stdm\stdm.py", line 30, in 
    from ui import (
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Olivier/.qgis2/python/plugins\stdm\ui\__init__.py", line 4, in 
    from .manage_accounts_dlg import manageAccountsDlg
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Olivier/.qgis2/python/plugins\stdm\ui\manage_accounts_dlg.py", line 19, in 
    from ui_user_role_manage import Ui_frmSysManageAccounts
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Olivier/.qgis2/python/plugins\stdm\ui\ui_user_role_manage.py", line 129, in 
    import resources_rc
  File "R:/Apps/OSGeo4W64/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources_rc
```

In my version of QGIS, when I go to the plugin manager, the STDM model is displayed in red, with this error message.
**This plugin is broken No module named ui_edit_stdm_layer**

In the QGIS for STDM version, I don't see the plugin at all.

Am I missing something ?

Thanks,

Olivier

**Comment by olivierdalang** [comment]
Note : I just tried to install using the repository ( http://stdm.gltn.net/plugin/plugins.xml ) and there it works !
So you may discard my question, maybe it would be nice to put the repoitory link in the readme ?

Bests regards,

Olivier

**Comment by gkahiu** [comment]
Hi Olivier,

Great to here that it is working though we have not encountered that issue
before but will investigate further. Thanks for the suggestion.

Regards,

John

**Comment by eomwandho** [comment]
@olivierdalang which operating system are you using?

**Comment by gkahiu** [comment]
This has been fixed in master
