### ISSUE TITLE
Stack Trace when opening the Document Designer

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#405]
Am getting the following stack trace when I open the _Document Designer_.

`AttributeError: 'ComposerWrapper' object has no attribute '_compView' 
Traceback (most recent call last):
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\plugin.py", line 1789, in onDocumentDesigner
    composerWrapper.configure()
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\composer\composer_wrapper.py", line 286, in configure
    ciConfig(self)
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\composer\composer_item_config.py", line 154, in __init__
    ComposerItemConfig.__init__(self, composerWrapper)
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\composer\composer_item_config.py", line 67, in __init__
    self.composerView().actionFinished.connect(self.onActionFinished)
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\composer\composer_item_config.py", line 104, in composerView
    return self._composerWrapper.composerView()
  File "C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\composer\composer_wrapper.py", line 322, in composerView
    return self._compView
AttributeError: 'ComposerWrapper' object has no attribute '_compView'
`

**Comment by nyalldawson** [comment]
Was this testing using https://github.com/gltn/stdm/pull/401 ?
