### ISSUE TITLE
Stack trace when searching for records in module View STR

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#427]
The module View STR throws a stack trace when you search for records on tabs that represent spatial units.

`An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:/Users/marko/.qgis2/python/plugins\stdm\ui\view_str.py", line 463, in searchEntityRelations
    entity, result_ids
  File "C:/Users/marko/.qgis2/python/plugins\stdm\ui\feature_details.py", line 1042, in search_spatial_unit
    self.feature_models.keys()
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted`

**Comment by nyalldawson** [comment]
I can't reproduce this one on master -- I suspect it's been solved by other related fixes
