### ISSUE TITLE
Error adding a second spatial unit record.

### ISSUE THREAD

**Issue by juhudiduparc** [gltn/stdm#457]
An error has occurred while executing Python code: 

AttributeError: 'list' object has no attribute 'id' 
Traceback (most recent call last):
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\forms\spatial_unit_form.py", line 251, in 
    lambda feature_id: self.load_stdm_form(
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\forms\spatial_unit_form.py", line 477, in load_stdm_form
    self.editor = EntityEditorDialog(
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\forms\editor_dialog.py", line 192, in __init__
    self._init_gui(show_str_tab=allow_str_creation and self.participates_in_str, is_party_unit=self.is_party_unit)
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\forms\editor_dialog.py", line 236, in _init_gui
    self._setup_str_tab(is_party_unit=is_party_unit)
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\forms\editor_dialog.py", line 672, in _setup_str_tab
    self.details_tree_view.search_spatial_unit(self.entity, [self.ent_model.id])
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\feature_details.py", line 992, in search_spatial_unit
    self.add_root_children(db_model, root, str_records)
  File "C:\Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\stdm\ui\feature_details.py", line 1153, in add_root_children
    feature_id = model.id
AttributeError: 'list' object has no attribute 'id'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.8-Hannover Hannover, 8c50902e 

![image](https://user-images.githubusercontent.com/21189476/131843017-52902550-50fb-4229-95d3-42fa65c0ce3b.png)

**Comment by pgathogo** [comment]
@juhudiduparc this is noted, however, could you kindly elaborate what activity you were doing when you encountered this error?
