### ISSUE TITLE
Stack trace when uploading scanned documents

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#476]
@strabzounly

An error has occurred while executing Python code: 

KeyError: 'scanned_cert_ref_column' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\document_uploader.py", line 136, in uploader_thread_started
    self.upload_worker.start_upload()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\document_uploader.py", line 201, in start_upload
    self.upload_scanned_certs(scanned_certs)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\document_uploader.py", line 209, in upload_scanned_certs
    ref_column = self.support_doc_map['scanned_cert_ref_column']
KeyError: 'scanned_cert_ref_column'

**Comment by strabzounly** [comment]
Correct,
You are kindly requested to add line  
"scanned_cert_ref_column=claim_ref_number"
to the section "[support_doc-map]"
in the mapping file "property_mapfile.ini"

```
[support_doc-map]
main_table=hl_supporting_document
parent_table=hl_property
parent_ref_column=kobo_submission_id
parent_support_table=hl_property_supporting_document
doc_type_lookup_table=hl_check_property_document_type
src_key_field_column=col_e_76
**scanned_cert_ref_column=claim_ref_number**
```
