### ISSUE TITLE
Error when allowing supporting document for an entity

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#55]
When I tried to allow supporting document for an entity in configuration wizard's Profile Entities, Edit button, and check 'allow supporting document' and click ok, the entity disappears from the box. 
When I try to repeat the same in another entity, I get the following error.

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\create_entity.py", line 130, in accept
    if self.add_entity():
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\create_entity.py", line 103, in add_entity
    self.profile.remove_entity(entity_name)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\profile.py", line 345, in remove_entity
    ent_replica = ent.clone()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity.py", line 234, in clone
    return deepcopy(self)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\Python27\lib\copy.py", line 172, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
RuntimeError: super-class __init__() of type Entity was never called

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/Users/Wondim/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']

**Comment by pgathogo** [comment]
@gkahiu , kindly comment on this.

**Comment by gkahiu** [comment]
Dear Wondie,

This is a known bug. Am working on a fix.

**Comment by wondie** [comment]
This issue is now fixed!
