### ISSUE TITLE
Stack Trace when Updating Existing Profile with a new lookup

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#58]
I tried to update the existing profile with new lookup called gender but I got a stack trace when I clicked on the Finish button. The error is not caused by the new lookup but the existing lookup, check_tenure_type.  Below is the full error message. 

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 404, in _updater_thread_started
    self.config_updater.exec_()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\config_updater.py", line 93, in exec_
    self.update_profile(p)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\config_updater.py", line 154, in update_profile
    self._update_entities(profile.entities.values())
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\config_updater.py", line 187, in _update_entities
    e.update(self.engine, self.metadata)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity.py", line 258, in update
    self.sql_updater(engine, metadata)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity_updaters.py", line 189, in value_list_updater
    lookup_obj.delete()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\database.py", line 252, in delete
    db.session.commit()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 555, in execute
    uow
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 117, in delete_obj
    cached_connections, mapper, table, delete)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 694, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) update or delete on table "tu_check_tenure_type" violates foreign key constraint "tu_social_tenure_relationship_tenure_type_fkey" on table "tu_social_tenure_relationship"
DETAIL:  Key (id)=(6) is still referenced from table "tu_social_tenure_relationship".
 'DELETE FROM tu_check_tenure_type WHERE tu_check_tenure_type.id = %(id)s' {'id': 6}

**Comment by gkahiu** [comment]
I will also try replicate it.

**Comment by wondie** [comment]
This issue is now fixed!
