### ISSUE TITLE
On delete and on update cascade missing for foreign key tables which causes an error

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#96]
On delete and on update cascade is set to No Action for foreign key tables such as social_tenure_relationship, and entity_supporting document tables. 

I couldn't delete a social tenure relationship because of the same issue. Blow is the error shown when deleting  an STR from view STR. 

An error has occured while executing Python code:

```

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\navigation\socialtenure\nodes.py", line 636, in 
    self.deleteAction.triggered.connect(lambda: self.onDelete(model_index))
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\navigation\socialtenure\nodes.py", line 604, in onDelete
    self._model.delete()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\database.py", line 252, in delete
    db.session.commit()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\unitofwork.py", line 555, in execute
    uow
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 117, in delete_obj
    cached_connections, mapper, table, delete)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\orm\persistence.py", line 694, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) update or delete on table "tu_social_tenure_relationship" violates foreign key constraint "tu_social_tenure_relationship_supporting_document_social_tenure" on table "tu_social_tenure_relationship_supporting_document"
DETAIL:  Key (id)=(177) is still referenced from table "tu_social_tenure_relationship_supporting_document".
 'DELETE FROM tu_social_tenure_relationship WHERE tu_social_tenure_relationship.id = %(id)s' {'id': 177}


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/Users/Wondim/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\
```stdm\\third_party\\fontTools']

**Comment by wondie** [comment]
This issue is fixed. Every all the related rows are deleted!
